# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbe0ebdcff39b904a5b6bbc97c476cd2dd96f460c37e2005f42852580ce630e96c51cbbce1bb0623857498d308bdb21e8b58df49160a409a70aa8de5df68ff14

test:
  secret_key_base: 1f3d7919c41c84d580e9312d31c3f293c938d235e4c5cb034e7c2ccca8d83e82c9169c1a70ce7bcd850be3438b0a80fc7535f1734175e1bf78c9a4519a5efaf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
